title: [Christina Hoidra]
description: [Detail-oriented and driven professional with experience in the pharmaceutical industry. Skilled in data organization, documentation, and communication. Motivated by data analytics opportunities in forensic and pharmaceutical industries to complete meaningful analysis that will have a positive impact on society and consumers.]
show_downloads: true
theme: jekyll-theme-cayman
