title: CHRISTINA HOIDRA
description: Data-focused professional with expertise in protocol development and data documentation gained in the pharmaceutical industry, with hands-on experience translating client requirements into structured documents. Skilled in data management, cross-functional collaboration, efficient execution, and adaptability in a fast-paced environment while maintaining high standards of data accuracy. Motivated by opportunities to leverage data-driven insights and streamline workflows within data analyst roles to support informed decision-making and operational excellence.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
