title: CHRISTINA HOIDRA
description: Skilled in data organization, documentation, and communication. Motivated by data analytics opportunities in forensic and pharmaceutical industries to complete meaningful analysis that will have a positive impact on society and consumers.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
